## SSMVD: Single Shot and Multi View based 3D-object Detection

In [1]:
import numpy as np

In [2]:
scales = np.linspace(0.15, 0.9, 6)
scales

array([ 0.15,  0.3 ,  0.45,  0.6 ,  0.75,  0.9 ])

In [3]:
scales * 300


array([  45.,   90.,  135.,  180.,  225.,  270.])

In [4]:
import tensorflow as tf

In [5]:
a = tf.constant(np.arange(0, 6), shape=(2, 3))

In [6]:
isess = tf.InteractiveSession()

In [7]:
isess.run(a)

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
a.get_shape().as_list()

[2, 3]

In [21]:
x, y = np.mgrid[0:10, 0:10]

In [22]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [31]:
x.shape

(10, 10)

In [23]:
y

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
xx = np.expand_dims(x, axis=-1)
yy = np.expand_dims(y, axis=-1)
xx

array([[[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]],

       [[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1]],

       [[2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2]],

       [[3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3],
        [3]],

       [[4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4]],

       [[5],
        [5],
        [5],
        [5],
        [5],
        [5],
        [5],
        [5],
        [5],
        [5]],

       [[6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6]],

       [[7],
        [7],
        [7],
        [7],
        [7],
        [7]

In [40]:
h = np.arange(4)
h.shape

(4,)

In [41]:
xx + h

array([[[ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 0,  1,  2,  3]],

       [[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4]],

       [[ 2,  3,  4,  5],
        [ 2,  3,  4,  5],
        [ 2,  3,  4,  5],
        [ 2,  3,  4,  5],
        [ 2,  3,  4,  5],
        [ 2,  3,  4,  5],
        [ 2,  3,  4,  5],
        [ 2,  3,  4,  5],
        [ 2,  3,  4,  5],
        [ 2,  3,  4,  5]],

       [[ 3,  4,  5,  6],
        [ 3,  4,  5,  6],
        [ 3,  4,  5,  6],
        [ 3,  4,  5,  6],
        [ 3,  4,  5,  6],
        [ 3,  4,  5,  6],
        [ 3,  4,  5,  6],
        [ 3,  4,  5,  6],
      

In [3]:
from urllib.request import urlretrieve
from os.path import isfile, isdir
from tqdm import tqdm
import tarfile

cifar10_dataset_folder_path = 'test'

class DLProgress(tqdm):
    last_block = 0

    def hook(self, block_num=1, block_size=1, total_size=None):
        self.total = total_size
        self.update((block_num - self.last_block) * block_size)
        self.last_block = block_num

if not isfile('VOCtrainval_06-Nov-2007.tar'):
    with DLProgress(unit='B', unit_scale=True, miniters=1, desc='CIFAR-10 Dataset') as pbar:
        urlretrieve(
            'http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar',
            'VOCtrainval_06-Nov-2007.tar',
            pbar.hook)

if not isdir(cifar10_dataset_folder_path):
    with tarfile.open('VOCtrainval_06-Nov-2007.tar') as tar:
        tar.extractall()
        tar.close()

CIFAR-10 Dataset:   2%|▏         | 9.32M/460M [00:17<16:12, 463KB/s]    


KeyboardInterrupt: 